name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone because Nerdbank.GitVersioning requires the full history
      - name: Install libssl1.1
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
      - name: Pack (create NuGet package)
        run: dotnet pack "src\Dropsonic.AspNetCore.Routing\Dropsonic.AspNetCore.Routing.csproj" --configuration Release --no-build --output .
      - name: Archive NuGet package as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: "*.nupkg"
          retention-days: 3
