name: Publish NuGet package

on:
  push:
    paths:
      - "version.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
      - name: Publish
        uses: dotnet nuget push *.nupkg --api-key ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
