name: Publish

on:
  push:
    paths:
      - "version.json"
      - ".github/workflows/publish.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download the artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          name: nuget-package
          path: .
      - name: Publish
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY} --skip-duplicates
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
