name: Publish

on:
  push:
    paths:
      - "version.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download the artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          name: nuget-package
          path: .
      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
